version: 2
updates:
  - package-ecosystem: npm
    allow:
      - dependency-type: direct
    directory: /frontend/pratiler-frontend
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    target-branch: main
  - package-ecosystem: github-actions
    allow:
      - dependency-type: direct
    directory: /workflows
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    target-branch: main